# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15.0
      - image: mongo:4.0.1
        port: 27017:27017
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run linter
          name: lint
          command: npm run lint
      - run: # run tests
          name: test
          command: npm run test-ci
          environment:
            CRYPTO_SECRET: circlecitestcirclecitestcircleci
            CRYPTO_ALGORITHM: aes-192-cbc
            TOKEN_SECRET: circlesecret
            SERVICE_ENV: ci
